Repository NageshMandal/Engineering-Notes-Website, pull requests merged in 2022-10, with the labels that each got.

#17 fixed navbar bug and added more styles in footer
  index.html
  style.css
Labels: Hacktoberfest, hacktoberfest accepted

#21 Updated README.md
  README.md
Labels: bug, Hacktoberfest, hacktoberfest accepted

#25 Update footer
  index.html
  style.css
Labels: enhancement, Hacktoberfest, hacktoberfest accepted

#26 Fixed position of mic in mobile view
  style.css
Labels: bug, Hacktoberfest, hacktoberfest accepted

#29 Changed footer of all branches, applied same scrollbar styling as Index.html and fixed Typing Errors
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
Labels: enhancement, Hacktoberfest, hacktoberfest accepted

#32 Add voice recognition features
  app.js
  index.html
Labels: bug, enhancement, Hacktoberfest, hacktoberfest accepted

#34 Favicon added
  images/favicon.png
  index.html
Labels: Hacktoberfest, hacktoberfest accepted
