Repository NageshMandal/Engineering-Notes-Website, pull requests merged in 2023-07, with the labels that each got.

#887 improved ui of syllabus page
  images/syllabus/syll_icon.png
  images/syllabus/syllabus.png
  style.css
  syllabus.css
  syllabus.html
Labels: gssoc23, level2

#901 3rd Sem electrical engineering downliad page ui design
  images/3rd sem electrical.png
  images/3rd sem.png
Labels: gssoc23, level2

#902 2nd sem civil download page ui design
  images/2nd sam civil.png
Labels: gssoc23, level2

#903 3rd Sem CSE Download page ui design
  images/3rd sem cse.png
Labels: gssoc23, level2

#898 placement section improved #888
  placement.html
  style.css
Labels: gssoc23, level2

#934 ECE Download Page
  images/04.07.2023_22.40.40_REC.png
Labels: gssoc23, level2

#932 Update library.html
  library.html
Labels: gssoc23, level1

#935 CEC Download page
  images/04.07.2023_22.40.56_REC.png
Labels: gssoc23, level2

#907 faqs added
  index.html
  style.css
Labels: gssoc23, level2

#900 Enhance footer
  index.html
  style.css
Labels: gssoc23, level1

#965 Contact us form validated
  contactus.html
Labels: gssoc23, level2

#971 UI Design download page for electrical engineering
  images/07.07.2023_23.36.09_REC.png
Labels: gssoc23, level2

#999 civil 3rd and 4th sem download page UI design figma
  figma.txt
Labels: gssoc23, level2

#1000 Civil 4th sem download page
  images/15.07.2023_18.54.10_REC.png
Labels: gssoc23, level2

#1014 Change in css in dark mode of the syllabus section #1012
  style.css
  syllabus.css
Labels: gssoc23, level1

#1019 EE figma 4th sem branch page
  figma.txt
  images/19.07.2023_16.18.53_REC.png
Labels: gssoc23, level2

#1027 adding 3d animation in the student image #1026
  style.css
Labels: gssoc23, level1

#978 Added the MIT License badge and changed the license section
  README.md
Labels: gssoc23, level1

#1070 Download Page Figma UI Design
  figma.txt
  images/21.07.2023_21.23.11_REC.png
Labels: gssoc23, level2

#1069 Adding AI Chat and Voice Assistant for FAQ, Navigation, and User Experience Improvement
  Gallary-section/index.html
  about.html
  contact.html
  contactus.html
  event.html
  index.html
  library.html
  placement.html
  projects.html
  script.js
  syllabus.html
Labels: gssoc23, level3

#1071 Figma Design For branch
  figma.txt
  images/21.07.2023_21.22.51_REC.png
Labels: gssoc23, level2

#1073 added changes for sticky nav bar
  Gallary-section/index.html
  Gallary-section/style.css
  about.css
  contactus.css
  style.css
  syllabus.css
  syllabus.html
Labels: gssoc23, level2

#1049 fix: adding event section in the navbar in gallery section #1041
  Gallary-section/index.html
Labels: gssoc23, level1

#1083 Updated figma links for download pages
  figma.txt
Labels: gssoc23, level2

#1093 Electrical Engineering 5th sem download page
  images/27.07.2023_21.14.04_REC.png
Labels: gssoc23, level2

#1094 Civil Engineering 5Th sem download page
  images/27.07.2023_21.13.29_REC.png
Labels: gssoc23, level2
