Repository NageshMandal/Engineering-Notes-Website, pull requests merged in 2023-06, with the labels that each got.

#490 Adding new design in Contact Section
  index.html
Labels: gssoc23, Level1

#503 Added contact page
  contactus.css
  contactus.html
  index.html
Labels: gssoc23, Level2

#521 download page ui design
  images/03.06.2023_16.05.55_REC.png
Labels: gssoc23, Level1

#341 updated CONTRIBUTING.md. edited out some error.
  CONTRIBUTING.md
Labels: gssoc23, Level1

#529 Added the about page and linked to the homepage. [GSSoC]
  about.css
  about.html
  index.html
Labels: gssoc23, Level2

#528 changes done in style.css for footer part
  style.css
Labels: gssoc23, Level1

#525 library ui improved(video attached) without changing base design #471
  library.css
  library.html
  style.css
Labels: gssoc23, Level2

#537 Library section made responsive (Photos attached) #471
  library.css
Labels: gssoc23, Level2

#452 Resolved issue (#125) Updated Readme with Screenshots & Links
  README.md
  images/ss-1.PNG
  images/ss-2.PNG
Labels: gssoc23, Level1

#571 Changed the style keeping in mind the actual style of cards.
  Gallary-section/index.html
  Gallary-section/style.css
Labels: gssoc23, Level2

#569 Issue 533 solved
  index.html
  style.css
Labels: gssoc23, Level1

#623 Fixed Nav menu on Gallery(index.html)
  Gallary-section/index.html
Labels: gssoc23, Level1

#604 Added CSE books
  images/book13.png
  images/book14.png
  images/book15.png
  images/book16.png
  images/book17.png
  library.html
Labels: gssoc23, Level2

#546 Improvised placments page( hiring partners)
  images/hiring partners/13-1.jpg
  images/hiring partners/13-2.jpg
  images/hiring partners/13-3.png
  images/hiring partners/13-4.png
  images/hiring partners/13-5.jpg
  images/hiring partners/13-6.png
  images/hiring partners/13-7.png
  images/hiring partners/14-1.jpg
  images/hiring partners/14-10.jpg
  images/hiring partners/14-2.png
  images/hiring partners/14-3.jpg
  images/hiring partners/14-4.jpg
  images/hiring partners/14-5.jpg
  images/hiring partners/14-6.jpg
  images/hiring partners/14-7.jpg
  images/hiring partners/14-8.jpg
  images/hiring partners/14-9.png
  images/hiring partners/15-1.jpg
  images/hiring partners/15-2.jpg
  images/hiring partners/15-3.png
  images/hiring partners/15-4.png
  images/hiring partners/15-5.png
  images/hiring partners/15-6.png
  placement.html
  style.css
Labels: gssoc23, Level2

#652 Civil 1st year Download page
  images/civil 1st year download page.png
Labels: gssoc23, Level1

#660 updated the contributors list in README.md
  README.md
Labels: gssoc23, Level1

#671 UI and responsiveness improvement
  branch/style.css
  style.css
Labels: gssoc23, Level1

#695 Improved UI of Contact Page
  .vscode/settings.json
  contactus.css
  contactus.html
  images/menu-icon.png
Labels: gssoc23, Level2

#704 Adding Syllabus Section with assigned issues covered
  about.html
  app.js
  contactus.html
  images/syllabus/syllabus_icon_1.png
  images/syllabus/syllabus_icon_2.png
  images/syllabus/syllabus_icon_3.png
  index.html
  library.html
  placement.html
  projects.html
  script.js
  style.css
  syllabus.css
  syllabus.html
Labels: gssoc23, Level3

#705 Added the backtotop button in gallery
  Gallary-section/index.html
Labels: gssoc23, Level1

#713 change the text css and add cursor pointer to project submit
  style.css
Labels: gssoc23, Level1

#727 Updated UI Designs For Websites
  figma.txt
Labels: gssoc23, level2

#719 Added proper navigation to the department sections for home and contact us section
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
  index.html
Labels: gssoc23, level1

#728 New Navbar UI Design
  18.06.2023_19.06.27_REC.png
  figma.txt
Labels: gssoc23, level2

#738 Added navigation to home and about us page
  about.html
Labels: gssoc23, level1

#757 Fixed logo orientation
  .vscode/settings.json
  style.css
Labels: gssoc23, level1

#758 Projectsection #729
  library.css
  projects.html
  style.css
Labels: gssoc23, level1

#772 search button fixed
  style.css
Labels: gssoc23, level1

#782 New Navbar added to Home Page
  images/Logonew.png
  images/Moontoggle.png
  index.html
  style.css
Labels: gssoc23, level3

#788 Added the new navbar to all the sites
  Gallary-section/index.html
  Gallary-section/style.css
  about.html
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
  contact.html
  contactus.css
  contactus.html
  library.css
  library.html
  placement.html
  projects.html
  syllabus.html
Labels: gssoc23, level2

#786 Added 4 New Books In Library Page
  images/book24.png
  images/book25.png
  images/book26.png
  images/book27.png
  images/book28.png
  library.html
Labels: gssoc23, level1

#861 New UI Page for download page
  images/20.06.2023_14.38.29_REC.png
Labels: gssoc23, level2

#833 Added navigation to gallery page
  Gallary-section/index.html
  style.css
Labels: gssoc23, level1

#883 Contact Us Page Updated
  contactus.css
  contactus.html
Labels: gssoc23, level2

#882 Add [feat(event)]: added event section in the project
  about.html
  contact.html
  contactus.html
  event.css
  event.html
  index.html
  library.html
  placement.html
  projects.html
  style.css
  syllabus.html
Labels: gssoc23, level3

#862 Gallery Images Fixed
  Gallary-section/index.html
Labels: gssoc23, level1
