Repository NageshMandal/Engineering-Notes-Website, pull requests merged in 2023-05, with the labels that each got.

#66 Return to top arrow
  index.html
  script.js
  style.css
Labels: enhancement, GSSOC23

#64 links in the Icons of social sites in the footer is fixed
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
  index.html
Labels: good first issue, GSSOC23

#104 Enhance Footer Links' Visibility/UI on Hover
  style.css
Labels: good first issue, GSSOC23

#93 Navigation correction
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
  branch/subjects/1st/ce.html
  branch/subjects/1st/cse.html
  branch/subjects/1st/ece.html
  branch/subjects/1st/ee.html
  branch/subjects/1st/me.html
  branch/subjects/2nd/ce.html
  branch/subjects/2nd/cse.html
  branch/subjects/2nd/ece.html
  branch/subjects/2nd/ee.html
  branch/subjects/2nd/me.html
  branch/subjects/3rd/ce.html
  branch/subjects/3rd/cse.html
  branch/subjects/3rd/ece.html
  branch/subjects/3rd/ee.html
  branch/subjects/3rd/me.html
  branch/subjects/4th/ce.html
  branch/subjects/4th/cse.html
  branch/subjects/4th/ece.html
  branch/subjects/4th/ee.html
  branch/subjects/4th/me.html
  branch/subjects/5th/ce.html
  branch/subjects/5th/cse.html
  branch/subjects/5th/ece.html
  branch/subjects/5th/ee.html
  branch/subjects/5th/me.html
  branch/subjects/6th/ce.html
  branch/subjects/6th/cse.html
  branch/subjects/6th/ece.html
  branch/subjects/6th/ee.html
  branch/subjects/6th/me.html
  branch/subjects/7th/ce.html
  branch/subjects/7th/cse.html
  branch/subjects/7th/ece.html
  branch/subjects/7th/ee.html
  branch/subjects/7th/me.html
  branch/subjects/8th/ce.html
  branch/subjects/8th/cse.html
  branch/subjects/8th/ece.html
  branch/subjects/8th/ee.html
  branch/subjects/8th/me.html
Labels: good first issue, GSSOC23

#136 Issue 124
  index.html
  style.css
Labels: good first issue, GSSOC23

#174 feat: improve notes page layout
  branch/subjects/1st/ce.html
  branch/subjects/1st/cse.html
  branch/subjects/1st/ece.html
  branch/subjects/1st/ee.html
  branch/subjects/1st/me.html
  branch/subjects/2nd/ce.html
  branch/subjects/2nd/cse.html
  branch/subjects/2nd/ece.html
  branch/subjects/2nd/ee.html
  branch/subjects/2nd/me.html
  branch/subjects/3rd/ce.html
  branch/subjects/3rd/cse.html
  branch/subjects/3rd/ece.html
  branch/subjects/3rd/ee.html
  branch/subjects/3rd/me.html
  branch/subjects/4th/ce.html
  branch/subjects/4th/cse.html
  branch/subjects/4th/ece.html
  branch/subjects/4th/ee.html
  branch/subjects/4th/me.html
  branch/subjects/5th/ce.html
  branch/subjects/5th/cse.html
  branch/subjects/5th/ece.html
  branch/subjects/5th/ee.html
  branch/subjects/5th/me.html
  branch/subjects/6th/ce.html
  branch/subjects/6th/cse.html
  branch/subjects/6th/ece.html
  branch/subjects/6th/ee.html
  branch/subjects/6th/me.html
  branch/subjects/7th/ce.html
  branch/subjects/7th/cse.html
  branch/subjects/7th/ece.html
  branch/subjects/7th/ee.html
  branch/subjects/7th/me.html
  branch/subjects/8th/ce.html
  branch/subjects/8th/cse.html
  branch/subjects/8th/ece.html
  branch/subjects/8th/ee.html
  branch/subjects/8th/me.html
  branch/subjects/scripts/module-list.js
  branch/subjects/style.css
Labels: GSSOC23

#181 Fix the color changing issue
  index.html
  script.js
  style.css
Labels: good first issue, GSSOC23

#179 #159 Readme is updated with badges
  README.md
Labels: GSSOC23

#175 updated style.css
  style.css
Labels: GSSOC23

#206 Add CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: gssoc23, Level1

#205 Added Animated Underline Effect
  .DS_Store
  branch/style.css
  package-lock.json
Labels: gssoc23, Level1

#190 Added Phone Icon to the footer
  .vscode/settings.json
  index.html
  style.css
Labels: gssoc23, Level1

#147 footer-links-section UI modified
  style.css
Labels: gssoc23, Level1

#282 Implemented dark mode in all Branches
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
  branch/theme.js
Labels: gssoc23, Level2

#237 #163 Gallay Section completed
  Gallary-section/images/i1.png
  Gallary-section/images/m10.jpg
  Gallary-section/images/m11.jpg
  Gallary-section/images/m111.jpg
  Gallary-section/images/m2.jpg
  Gallary-section/images/m222.jpg
  Gallary-section/images/m3.jpg
  Gallary-section/images/m333.png
  Gallary-section/images/m444.png
  Gallary-section/images/m5.jpeg
  Gallary-section/images/m55.jpg
  Gallary-section/images/m555.jpg
  Gallary-section/images/m6.jpg
  Gallary-section/images/m77.jpg
  Gallary-section/images/m8.jpg
  Gallary-section/images/m9.jpg
  Gallary-section/images/microphone-solid.svg
  Gallary-section/index.html
  Gallary-section/style.css
  index.html
Labels: gssoc23, Level3

#235 Branch favicon is updated
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
Labels: gssoc23, Level2

#322 Corrected a misspell, and added a link. [GSSoC'23]
  Gallary-section/index.html
Labels: gssoc23, Level1

#321 Adding 3rd Sem notes
  branch/subjects/3rd/cse.html
  branch/subjects/4th/cse.html
Labels: gssoc23, Level1

#338 added contributors list to main homepage
  index.html
  script.js
  style.css
Labels: gssoc23, Level2

#129 fix : Fix typo in project
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
  branch/subjects/1st/ce.html
  branch/subjects/1st/cse.html
  branch/subjects/1st/ece.html
  branch/subjects/1st/ee.html
  branch/subjects/1st/me.html
  branch/subjects/2nd/ce.html
  branch/subjects/2nd/cse.html
  branch/subjects/2nd/ece.html
  branch/subjects/2nd/ee.html
  branch/subjects/2nd/me.html
  branch/subjects/3rd/ce.html
  branch/subjects/3rd/cse.html
  branch/subjects/3rd/ece.html
  branch/subjects/3rd/ee.html
  branch/subjects/3rd/me.html
  branch/subjects/4th/ce.html
  branch/subjects/4th/cse.html
  branch/subjects/4th/ece.html
  branch/subjects/4th/ee.html
  branch/subjects/4th/me.html
  branch/subjects/5th/ce.html
  branch/subjects/5th/cse.html
  branch/subjects/5th/ece.html
  branch/subjects/5th/ee.html
  branch/subjects/5th/me.html
  branch/subjects/6th/ce.html
  branch/subjects/6th/cse.html
  branch/subjects/6th/ece.html
  branch/subjects/6th/ee.html
  branch/subjects/6th/me.html
  branch/subjects/7th/ce.html
  branch/subjects/7th/cse.html
  branch/subjects/7th/ece.html
  branch/subjects/7th/ee.html
  branch/subjects/7th/me.html
  branch/subjects/8th/ce.html
  branch/subjects/8th/cse.html
  branch/subjects/8th/ece.html
  branch/subjects/8th/ee.html
  branch/subjects/8th/me.html
Labels: gssoc23, Level1

#391 add a searchbar
  index.html
  projects.html
  script.js
Labels: gssoc23, Level2

#361 issue #120 SEO of Complete website done
  branch/CE.html
  branch/ME.html
  branch/cs.html
  branch/ece.html
  branch/ee.html
  branch/subjects/1st/ce.html
  branch/subjects/1st/cse.html
  branch/subjects/1st/ece.html
  branch/subjects/1st/ee.html
  branch/subjects/1st/me.html
  branch/subjects/2nd/ce.html
  branch/subjects/2nd/cse.html
  branch/subjects/2nd/ece.html
  branch/subjects/2nd/ee.html
  branch/subjects/2nd/me.html
  branch/subjects/3rd/ce.html
  branch/subjects/3rd/cse.html
  branch/subjects/3rd/ece.html
  branch/subjects/3rd/ee.html
  branch/subjects/3rd/me.html
  branch/subjects/4th/ce.html
  branch/subjects/4th/cse.html
  branch/subjects/4th/ece.html
  branch/subjects/4th/ee.html
  branch/subjects/4th/me.html
  branch/subjects/5th/ce.html
  branch/subjects/5th/cse.html
  branch/subjects/5th/ece.html
  branch/subjects/5th/ee.html
  branch/subjects/5th/me.html
  branch/subjects/6th/ce.html
  branch/subjects/6th/cse.html
  branch/subjects/6th/ece.html
  branch/subjects/6th/ee.html
  branch/subjects/6th/me.html
  branch/subjects/7th/ce.html
  branch/subjects/7th/cse.html
  branch/subjects/7th/ece.html
  branch/subjects/7th/ee.html
  branch/subjects/7th/me.html
  branch/subjects/8th/ce.html
  branch/subjects/8th/cse.html
  branch/subjects/8th/ece.html
  branch/subjects/8th/ee.html
  branch/subjects/8th/me.html
  index.html
Labels: gssoc23, Level3

#371 Library Added #312 solved
  images/book1.jpg
  images/book10.jpg
  images/book11.jpg
  images/book12.jpg
  images/book2.jpg
  images/book3.jpg
  images/book4.jpg
  images/book5.jpg
  images/book6.jpg
  images/book7.jpg
  images/book8.jpg
  images/book9.jpg
  index.html
  library.css
  library.html
  library.js
Labels: gssoc23, Level2
